### ISSUE TITLE
第十二章 集合

### ISSUE THREAD

**Issue by 1326670425** [LingCoder/OnJava8#108]
* [第十二章 集合](docs/book/12-Collections.md)
    * [泛型和类型安全的集合](docs/book/12-Collections.md#泛型和类型安全的集合)
    * [基本概念](docs/book/12-Collections.md#基本概念)
    * [添加元素组](docs/book/12-Collections.md#添加元素组)
    * [集合的打印](docs/book/12-Collections.md#集合的打印)
    * [列表List](docs/book/12-Collections.md#列表List)
    * [迭代器Iterators](docs/book/12-Collections.md#迭代器Iterators)
    * [链表LinkedList](docs/book/12-Collections.md#链表LinkedList)
    * [堆栈Stack](docs/book/12-Collections.md#堆栈Stack)
    * [集合Set](docs/book/12-Collections.md#集合Set)
    * [映射Map](docs/book/12-Collections.md#映射Map)
    * [队列Queue](docs/book/12-Collections.md#队列Queue)
    * [集合与迭代器](docs/book/12-Collections.md#集合与迭代器)
    * [for-in和迭代器](docs/book/12-Collections.md#for-in和迭代器)
    * [本章小结](docs/book/12-Collections.md#本章小结)

**Comment by sjsdfg** [comment]
翻译完成
