### ISSUE TITLE
第二十四章 - 并发编程

### ISSUE THREAD

**Issue by blackwatchcup** [LingCoder/OnJava8#112]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* [第二十四章 并发编程](docs/book/24-Concurrent-Programming.md)
    * [术语问题](docs/book/24-Concurrent-Programming.md#术语问题)
    * [并发的超能力](docs/book/24-Concurrent-Programming.md#并发的超能力)
    * [针对速度](docs/book/24-Concurrent-Programming.md#针对速度)
    * [四句格言](docs/book/24-Concurrent-Programming.md#四句格言)
    * [残酷的真相](docs/book/24-Concurrent-Programming.md#残酷的真相)
    * [本章其余部分](docs/book/24-Concurrent-Programming.md#本章其余部分)
    * [并行流](docs/book/24-Concurrent-Programming.md#并行流)
    * [创建和运行任务](docs/book/24-Concurrent-Programming.md#创建和运行任务)
    * [终止耗时任务](docs/book/24-Concurrent-Programming.md#终止耗时任务)
    * [CompletableFuture类](docs/book/24-Concurrent-Programming.md#CompletableFuture类)
    * [死锁](docs/book/24-Concurrent-Programming.md#死锁)
    * [构造函数非线程安全](docs/book/24-Concurrent-Programming.md#构造函数非线程安全)
    * [复杂性和代价](docs/book/24-Concurrent-Programming.md#复杂性和代价)
    * [本章小结](docs/book/24-Concurrent-Programming.md#本章小结)

**Comment by sjsdfg** [comment]
把原来的 issue 关掉了

**Comment by wrmu** [comment]
> 把原来的 issue 关掉了

这章我来，进度一周一小节。

**Comment by 1163710133** [comment]
现有译文发现了一些错别字，如何申请成为校对？

**Comment by sjsdfg** [comment]
> 现有译文发现了一些错别字，如何申请成为校对？

直接发起 PR 修改错别字就好

**Comment by yuzhiboxxx** [comment]
......
