### ISSUE TITLE
第十一章 内部类 目录与正文标题对应不上

### ISSUE THREAD

**Issue by OrdinaryYZH** [LingCoder/OnJava8#137]
例如：目录上写着"内部类应用场景"，但是内容却没有此标题

**Comment by sjsdfg** [comment]
一切以实际翻译内容为准。
目录里面的翻译有可能在翻译过程中觉得并不合适，因此会出现题目翻译变更的情况。

**Comment by OrdinaryYZH** [comment]
所以不是应该修改一下目录，优化一下用户体验吗？

**Comment by sjsdfg** [comment]
> 所以不是应该修改一下目录，优化一下用户体验吗？

项目翻译后期还需要校对，这都不是定稿。
如果你觉得不合适，我们更期望你自己提交 PR 来进行更新。
这个项目非常开放，而且门槛相对较低。
期待你的参与
