### ISSUE TITLE
第六章 初始化和清理 前五小节 翻译

### ISSUE THREAD

**Issue by binyulan** [LingCoder/OnJava8#14]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* 第六章 初始化和清理
  * 利用构造器保证初始化
  * 方法重载
  * 无参构造器
  * this关键字
  * 垃圾回收器

**Comment by sjsdfg** [comment]
= =这特么手贱不小心链上了。。。这可咋玩

**Comment by xiaoxiongmaojk** [comment]
谢谢你们的辛勤付出，在阅读的过程中发现有2处可以改善的地方，可是不知道在哪提出合适，就提到这里了，如果不合适告诉我，我删掉。

1.this关键字 小节
如果你在一个类的方法里调用**其他该类中的方法**
⇒如果你在一个类的方法里调用**该类中的其他方法**

2.非静态实例初始化 小节
从输出看出，**示例初始化**子句是在两个构造器之前执行的。
⇒从输出看出，**实例初始化**子句是在两个构造器之前执行的。

**Comment by sjsdfg** [comment]
> 谢谢你们的辛勤付出，在阅读的过程中发现有2处可以改善的地方，可是不知道在哪提出合适，就提到这里了，如果不合适告诉我，我删掉。
> 
> 1.this关键字 小节
> 如果你在一个类的方法里调用**其他该类中的方法**
> ⇒如果你在一个类的方法里调用**该类中的其他方法**
> 
> 2.非静态实例初始化 小节
> 从输出看出，**示例初始化**子句是在两个构造器之前执行的。
> ⇒从输出看出，**实例初始化**子句是在两个构造器之前执行的。

可以自己提交 PR。我们这里会进行合并。
提交流程可以看 https://github.com/LingCoder/OnJava8/blob/master/CONTRIBUTING.md

同时这里也有单独的视频教程：https://www.bilibili.com/video/av58040840

大胆用这个来熟悉 git 的操作流程。这也是以后工作的必备技能

**Comment by sjsdfg** [comment]
@xiangflight 参译，并完成本章翻译
