### ISSUE TITLE
第三章 万物皆对象

### ISSUE THREAD

**Issue by liuningdev** [LingCoder/OnJava8#157]
###  申请翻译/校对

  * 校对

### 具体章节/标题

* 第三章 万物皆对象
  * 对象创建
    * 基本类型的存储	

最后一行“个中原因将在以后的章节里解释。”
修改为“各种原因将在以后的章节里解释。”

**Comment by LingCoder** [comment]
这个应该没错吧,体会下语义

**Comment by liuningdev** [comment]
> 这个应该没错吧,体会下语义

Sorry。无意中发现，没理解语义。建议修改为“其中原因”避免误读。
