### ISSUE TITLE
关于第一章翻译的一点疑问

### ISSUE THREAD

**Issue by YngwieWang** [LingCoder/OnJava8#173]
第一张继承部分有”基础类“、”基类“、”基本类型“和”基类型“，感觉初学者容易混淆，建议统一称谓，不知妥否。

**Comment by sjsdfg** [comment]
多人参译导致的。。。

回头群里统一校对统一一下吧

个人倾向于 ”基类“ 和 ”基本类型“
比较符合大家的常规认识

**Comment by YngwieWang** [comment]
我觉得”基类“更合适一些，前文有说 `class` 和 `type` 是同义词，并且”基本类型“有可能与”基本数据类型“混淆。：）

**Comment by sjsdfg** [comment]
嗯，你能直接发一个 pr 就更好了。

统一成”基类“吧

**Comment by YngwieWang** [comment]
OK，我来修改。
