### ISSUE TITLE
第三章 万物皆对象 static 的疑问

### ISSUE THREAD

**Issue by REBOOTERS** [LingCoder/OnJava8#176]
* 第三章 万物皆对象
  * static 关键字

```
class StaticTest {
    static int i = 47;
}

StaticTest st2 = new StaticTest();

```

> 引用静态变量有两种方法。在前面的示例中，我们通过一个对象来去定位它，例如 st2.i。我们也可以通过类名直接引用它

静态变量和静态方法，还可以通过对象引用直接调用吗 ？这个确定是这样吗？🤔🤔

**Comment by sjsdfg** [comment]
这种基础有什么可疑问的。。搞不懂
