### ISSUE TITLE
第三章 万物皆对象 中 基本类型的存储 int型和long型最大值

### ISSUE THREAD

**Issue by idhuanghui** [LingCoder/OnJava8#19]
第三章 万物皆对象 
 基本类型的存储 int型和long型最大值应为 + 2<sup>xx</sup>  -1

| 基本类型  |    大小 |  最小值  | 最大值  | 包装类型 |
| :------: | :------: | :------: | :------: | :------: |
| int | 32 bits | - 2<sup>31</sup> | + 2<sup>31</sup> -1 | Integer |  
| long | 64 bits | - 2<sup>63</sup> | + 2<sup>63</sup> -1 | Long |  
        
(int最大值应为+2<sup>31</sup>-1)
(long最大值应为+2<sup>63</sup>-1)

**Comment by LingCoder** [comment]
多谢提醒，笔误
