### ISSUE TITLE
第八章 复用 翻译

### ISSUE THREAD

**Issue by Langdon-Chen** [LingCoder/OnJava8#20]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* [第八章 复用](docs/book/08-Reuse.md)
    * [组合语法](docs/book/08-Reuse.md#组合语法)
    * [继承语法](docs/book/08-Reuse.md#继承语法)
    * [委托](docs/book/08-Reuse.md#委托)
    * [结合组合与继承](docs/book/08-Reuse.md#结合组合与继承)
    * [组合与继承的选择](docs/book/08-Reuse.md#组合与继承的选择)
    * [protected](docs/book/08-Reuse.md#protected)
    * [向上转型](docs/book/08-Reuse.md#向上转型)
    * [final关键字](docs/book/08-Reuse.md#final关键字)
    * [类初始化和加载](docs/book/08-Reuse.md#类初始化和加载)
    * [本章小结](docs/book/08-Reuse.md#本章小结)

**Comment by sjsdfg** [comment]
@xiangflight 参译本章节。
并完成本章节的翻译
