### ISSUE TITLE
第十六章 代码校验

### ISSUE THREAD

**Issue by RoyIronGrey** [LingCoder/OnJava8#223]
###  申请翻译/校对

  * 翻译

### 第十六章 代码校验

* 第十六章 代码校验
  * 测试驱动开发
  * 日志

**Comment by sjsdfg** [comment]
这个是我们给你关，还是你自己关？

或者是你继续翻译这一章的其他小节，继续关联这个 issue

**Comment by RoyIronGrey** [comment]
> 这个是我们给你关，还是你自己关？
> 
> 或者是你继续翻译这一章的其他小节，继续关联这个 issue

先不关吧，我有空就接着翻
