### ISSUE TITLE
代码格式

### ISSUE THREAD

**Issue by FantasticWW** [LingCoder/OnJava8#236]
第18章String的start()和end()章节的事例代码
static void examine(String s, String regex) {     
    Display d = new Display(regex);     
    Pattern p = Pattern.compile(regex);     
    Matcher m = p.matcher(s);     
    while(m.find())       
      d.display("find() '" + m.group() +         
        "' start = "+ m.start() + " end = " + m.end());     
      if(m.lookingAt()) // No reset() necessary       
        d.display("lookingAt() start = "         
          + m.start() + " end = " + m.end());     
      if(m.matches()) // No reset() necessary       
        d.display("matches() start = "         
          + m.start() + " end = " + m.end());   
  }   两个if是不是不用缩进

**Comment by sjsdfg** [comment]
你这粘贴过来就是挂的排版。看不出来你想问什么
用截图

**Comment by FantasticWW** [comment]
![1](https://user-images.githubusercontent.com/26758623/64221447-84b5cc80-ceff-11e9-8407-4c351c2d33e2.PNG)

**Comment by sjsdfg** [comment]
更没懂为什么不需要缩进
