### ISSUE TITLE
能否提供第二十五章-设计模式的pdf

### ISSUE THREAD

**Issue by Aiamjay** [LingCoder/OnJava8#242]
你好，我是一名cs专业master的学生，这学期在上一门Program Development Paradigm课程，这个课程是基于java的，主要学习设计模式。On Java 8中有对设计模式比较好的讲解，所以，能否帮忙，提供第二十五章的内容，感激不尽。如果我有多余的时间，会帮助贡献这本书的翻译。

**Comment by LingCoder** [comment]
可以加我们的翻译群下载,群共享里有呢

**Comment by Aiamjay** [comment]
谢谢，以及加群了，申请QQ号是 2634815874
