### ISSUE TITLE
附录 并发底层原理 章节翻译

### ISSUE THREAD

**Issue by AlfredAlan** [LingCoder/OnJava8#26]
###  申请翻译/校对

 * 翻译

### 具体章节/标题

* 附录:并发底层原理
   * 线程
   * 异常捕获
   * 资源共享
   * volatile关键字
   * 原子性
   * 关键部分
   * 库组件
   * 本章小结

**Comment by AlfredAlan** [comment]
仍然在翻译，重新认领  @sjsdfg

**Comment by blackwatchcup** [comment]
请问一下翻译到那一节了？

**Comment by AlfredAlan** [comment]
@blackwatchcup 目前到 volatile 关键字部分，后面部分预计月尾翻完
