### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by lian-xiao-xi** [LingCoder/OnJava8#269]
对【第九章 多态】-【转机】- 【陷阱：”覆写“私有方法】章节提出如下修改建议，详见下图

![image](https://user-images.githubusercontent.com/20748212/65863475-c4f35800-e3a2-11e9-9fe9-05a8607c8587.png)

**Comment by sjsdfg** [comment]
你有空提个 PR 么。除了这个问题之外。

把所有的 「覆写」也都改成「重写」，统一 override 的翻译
