### ISSUE TITLE
第十九章 类型信息 翻译

### ISSUE THREAD

**Issue by Moilk** [LingCoder/OnJava8#28]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* 第十九章 类型信息
  * 为什么需要 RTTI
  * Class 对象
  * 类型转换前先做检查
  * 注册工厂
  * instanceof 与 Class 的等价性
  * 反射：运行时的类型信息
  * 动态代理
  * 使用 Optional
  * 接口与类型信息
  * 本章小结

**Comment by LingCoder** [comment]
加油！谢谢参与。可以一节一节提交 pr，方便大家跟上校对。排版布局和翻译风格上参考**阮一峰**老师的 [中文技术文档的写作规范](https://github.com/ruanyf/document-style-guide)

**Comment by Moilk** [comment]
@sjsdfg 你好，这章还有一小节没有翻译完，因为之前有人一起翻译，所以我就从后面开始翻了（明天弄好）

**Comment by sjsdfg** [comment]
> @sjsdfg 你好，这章还有一小节没有翻译完，因为之前有人一起翻译，所以我就从后面开始翻了（明天弄好）

我看你的 pr 里面写着翻译完成。还以为已经翻完了
