### ISSUE TITLE
关于第一章:对象的概念的翻译的问题

### ISSUE THREAD

**Issue by codeOfLi** [LingCoder/OnJava8#304]
原文：在`The Progress of Abstraction` 中 `they were big improvements`
翻译这里“这类语言已有了长足的改进”’应该把`长足的进步`改为`很大的改进`把

**Comment by sjsdfg** [comment]
翻译。信雅达。

很大的进步你这就是直译了 

![image](https://user-images.githubusercontent.com/8037152/68573487-cedca080-04a2-11ea-8570-2db3f0e13d98.png)

没有觉得长足的进步有什么问题
