### ISSUE TITLE
泛型章节commit邮箱变更申请

### ISSUE THREAD

**Issue by siyuanzhou** [LingCoder/OnJava8#334]
在commit过程中，自己使用错误的邮箱格式提交，请求 @LingCoder 修改，万分感谢。

![image](https://user-images.githubusercontent.com/24700695/70297419-efd9ac80-1828-11ea-815b-c9cd937f8cc5.png)

修改代码如下：
```
#!/bin/sh
git filter-branch --env-filter '
OLD_EMAIL="siyuanzhou@163..com"
CORRECT_NAME="siyuanzhou"
CORRECT_EMAIL="siyuanzhou@163.com"
if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
```

**Comment by LingCoder** [comment]
没问题, 这个还没处理过= =! 我晚上回来研究下帮你改过来哈

**Comment by LingCoder** [comment]
不好意思啊,这个需要重写历史,会影响到所有fork和clone过这个项目的人.= =! 你可以在以后的提交中使用正确的邮箱,不必纠结之前的

**Comment by siyuanzhou** [comment]
收到，没事的，谢谢你啦！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LingCoder"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月5日(星期天) 晚上9:34
收件人:&nbsp;"LingCoder/OnJava8"<OnJava8@noreply.github.com&gt;;
抄送:&nbsp;"siyuanzhou"<siyuanzhou@163.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LingCoder/OnJava8] 泛型章节commit邮箱变更申请 (#334)




Closed #334.
