### ISSUE TITLE
第五章 控制流 存在疑点

### ISSUE THREAD

**Issue by KunMinX** [LingCoder/OnJava8#345]
内容不错，我是对照着 《C程序设计语言》来复习 java 的。

java 第五版原书我没有读过，但此处的描述存疑：

```
注解：else if 并非新关键字，它仅是 else 后紧跟的一条新 if 语句。
```

对此存疑，因为 else if 不仅仅是 else 后紧跟一条新的 if 语句，而是与 第一个 if ，以及最后一个 else（如果有）构成的一个完整的 **多路判断** 体（用 C 语言书的话来说）。

换言之，如果 走到 某个 else if 匹配了条件表达式，就会直接消费该 分支下的逻辑，以及终止整个 多路判断体 的后续运行。

综上，此处对于 else if 的说法存疑。

**Comment by sjsdfg** [comment]
![image](https://user-images.githubusercontent.com/8037152/71775340-32bea980-2fba-11ea-9e83-da80c794b383.png)
这本书只是做翻译用途。

我觉得应该是从不同的视角导致的理解歧义

这个提示明显是从“关键字”的角度来说。

从关键字的角度来说， else 和 if 是两个独立的关键字。

else if 只是两个关键字的组合而已。
而你的角度是从功能的角度来看的。 如果从"关键字"的角度来看，在 c 语言里面 else if 也并不是一个新的关键字，也是两个关键字的组合

**Comment by KunMinX** [comment]
@sjsdfg  感谢回复。现在，我在自己的笔记中这样描述了：else if 不是独立存在的关键字，是对 else 和 if 两个关键字的组合。

**Comment by KunMinX** [comment]
```java
if (xxxx) {
    yyyy
} else {
    if (zzzz) {
        www
    } else {
        if (hhhh) {
            kkkk
        } else {
            mmm
        }
    }
}
```			

懂了，说不定是承袭自 C 的语法糖。

也即 else 后面跟着的 if，是 else 代码块中的东西，是把整个 if 块中的东西当作了 else 块中的子句，而 if 后面的 else 又是和 if 并列成双。

所以才会导致一旦消费即终止的效果。

所以如果这不是语法糖，那就是语法本身这样规定，整个 if 或 if else 算作一个完整的执行语句。
