### ISSUE TITLE
《附录:成为一名程序员》

### ISSUE THREAD

**Issue by Hackergeek** [LingCoder/OnJava8#352]
![image](https://user-images.githubusercontent.com/9377994/72253210-fdf6c600-363b-11ea-942d-a6f9dadb2495.png)
这里翻译的是不是不太对，请问哪里可以找到英文版的pdf

**Comment by sjsdfg** [comment]
书在 q 群文件里面。

这个感觉翻译估计没啥问题。。因为这个句话看着像是有时代背景的
