### ISSUE TITLE
附录 成为一名程序员 章节翻译

### ISSUE THREAD

**Issue by hanwinbi** [LingCoder/OnJava8#36]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* 成为一名程序员
  * 如何开始
  * 码农生涯
  * 百分之五的神话
  * 重在动手
  * 像打字般编程
  * 做你喜欢的事

**Comment by LingCoder** [comment]
直接选大结局哈哈

**Comment by hanwinbi** [comment]
> 直接选大结局哈哈

太菜了，只能帮忙翻一下技术含量没那么高的部分了，哈哈哈

**Comment by LingCoder** [comment]
感谢贡献，希望坚持
