### ISSUE TITLE
个人认为关于“What’s impressive is it is not intellectually prohibitive to assemble such a model.”的翻译不正确

### ISSUE THREAD

**Issue by dellenovo** [LingCoder/OnJava8#362]
当前翻译：
令人印象深刻的是，组装这样的模型在理论上并不是禁止的。
改进后：
令人印象深刻的是，组装这样的模型并不需要耗费过多精力。
理由：
prohibitive在这里是代价高昂使人无法承受的意思，而不是禁止的意思。

**Comment by sjsdfg** [comment]
你可以提个 PR 么

**Comment by dellenovo** [comment]
> 你可以提个 PR 么

提好了。
