### ISSUE TITLE
第二十五章 设计模式

### ISSUE THREAD

**Issue by confucianzuoyuan** [LingCoder/OnJava8#372]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* 第二十五章 设计模式
  * 函数对象
  * 接口改变
  * 解释器
  * 回调
  * 多次调度
  * 模式重构
  * 抽象用法
  * 多次派遣
  * 访问者模式
  * RTTI的优劣
  * 本章小结

**Comment by LingCoder** [comment]
感谢贡献，希望坚持下去
