### ISSUE TITLE
第九章多态 构造器调用顺序 第七行翻译问题

### ISSUE THREAD

**Issue by bigpengry** [LingCoder/OnJava8#381]
翻译
> 这就是编译器强制每个派生类部分必须调用构造器的原因。

英文原文

>That’s why the compiler enforces a constructor call for every portion of a derived class.

个人感觉这句话应该理解为“这就是为什么编译器会强制调用每个派生类中的构造器”
 every portion 应该理解为每个派生类中的含有构造器的部分

**Comment by sjsdfg** [comment]
嗯，感觉你的更好些。

提个 PR 吧

**Comment by sjsdfg** [comment]
问题关了，别忘了 PR 啊

**Comment by bigpengry** [comment]
> 问题关了，别忘了 PR 啊
正在提了

**Comment by bigpengry** [comment]
> 问题关了，别忘了 PR 啊

正在提了
