### ISSUE TITLE
第十章 翻译讨论

### ISSUE THREAD

**Issue by ddtyjmyjm** [LingCoder/OnJava8#390]
“抽象类和方法”中有一句话：记住，事实上的访问权限是“friendly”。
查得项目提供的原文 Remember that the defacto access is “friendly.”

我怀疑这里“defacto”应该为“default”，不然整个段落语意说不通。

**Comment by sjsdfg** [comment]
感觉就应该是 default。。这个 defacto 也不知道是个啥。。。
