### ISSUE TITLE
第十九章 类型信息

### ISSUE THREAD

**Issue by Parkstud** [LingCoder/OnJava8#391]
###  申请校对
  * 校对
### 第十九章 类型信息
* Class 对象
  * 类字面常量
 

> 如果一个 static final 值是“编译期常量”（如 Initable.staticFinal），那么这个值不需要对 Initable 类进行初始化就可以被读取。但是，如果只是将一个字段设置成为 static 和 final，还不足以确保这种行为。例如，对 Initable.staticFinal2 的访问将强制进行类的初始化，因为它不是一个编译期常量。

应该是 "但是，如果只是将一个字段设置成为 static 或 final"

**Comment by sjsdfg** [comment]
提个 PR 吧
