### ISSUE TITLE
第三章 万物皆对象 - 校对

### ISSUE THREAD

**Issue by LiuXuelian09** [LingCoder/OnJava8#396]
###  申请翻译/校对

  * 校对

### 具体章节/标题

* 第三章 万物皆对象
  * 对象创建
  * 基本类型的存储
  * 高精度数值

**Comment by LiuXuelian09** [comment]
修改错别字：
 - 位置：小标题【高精度数值】的上面一句话，原文为：`个中原因将在以后的章节里解释。`
 - 建议：`个种原因将在以后的章节里解释。`

**Comment by sjsdfg** [comment]
。。。没觉得哪里改进了

**Comment by jiyewushen** [comment]
没见过'个种'这种用法
