### ISSUE TITLE
前言：语言设计错误

### ISSUE THREAD

**Issue by unclesesame** [LingCoder/OnJava8#415]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* 前言
  * 语言设计错误
 ”但这种糟糕的初学者经历比认识到你错了什么还要糟糕“改为"但这种糟糕的初学者经历比认识到你错在哪里还要糟糕"更通顺.

**Comment by LingCoder** [comment]
已改过来了，谢谢建议
