### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by wangguangwen98** [LingCoder/OnJava8#434]
动态数组创建
如果在编写程序时，不确定数组中需要多少个元素，那么该怎么办呢？你可以直接使用 new 在数组中创建元素。下面例子中，尽管创建的是基本类型数组，new 仍然可以工作（**不能用 new 创建单个的基本类型数组**）： 应该翻译为（**不能用 new 创建一个非数组的基本类型**）

**Comment by sjsdfg** [comment]
提 diff 吧

**Comment by LingCoder** [comment]
已修改，3Q
