### ISSUE TITLE
友情链接已失效

### ISSUE THREAD

**Issue by markofheaven** [LingCoder/OnJava8#438]
README.mk中的Effective.Java.3rd.Edition 中文版链接已经失效

**Comment by sjsdfg** [comment]
利益相关

友情链接是我的项目。

因为前段时间公众号没有经过我的授权瞎转发，被出版方版权警告了。

项目下线处理

**Comment by markofheaven** [comment]
> 利益相关
> 
> 友情链接是我的项目。
> 
> 因为前段时间公众号没有经过我的授权瞎转发，触犯了出版方的利益，被出版方版权警告了。
> 
> 项目下线处理

那暂时屏蔽这个链接体验是否会好一点呢

**Comment by SakuramiRin** [comment]
> 利益相关
> 
> 友情链接是我的项目。
> 
> 因为前段时间公众号没有经过我的授权瞎转发，触犯了出版方的利益，被出版方版权警告了。
> 
> 项目下线处理

啊啊，昨晚想克隆来着却没了，跪求orz
