### ISSUE TITLE
^2链接失效

### ISSUE THREAD

**Issue by markofheaven** [LingCoder/OnJava8#441]
第三章，万物皆对象，数据存储（https://github.com/LingCoder/OnJava8/blob/master/docs/book/03-Objects-Everywhere.md#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8）寄存器一段中，紧接“位于CPU内部”的"^2"所指向的链接已经失效

**Comment by teartao** [comment]
> 第三章，万物皆对象，数据存储（[https://github.com/LingCoder/OnJava8/blob/master/docs/book/03-Objects-Everywhere.md#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8）寄存器一段中，紧接“位于CPU内部”的"^2"所指向的链接已经失效](https://github.com/LingCoder/OnJava8/blob/master/docs/book/03-Objects-Everywhere.md#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8%EF%BC%89%E5%AF%84%E5%AD%98%E5%99%A8%E4%B8%80%E6%AE%B5%E4%B8%AD%EF%BC%8C%E7%B4%A7%E6%8E%A5%E2%80%9C%E4%BD%8D%E4%BA%8ECPU%E5%86%85%E9%83%A8%E2%80%9D%E7%9A%84%22%5E2%22%E6%89%80%E6%8C%87%E5%90%91%E7%9A%84%E9%93%BE%E6%8E%A5%E5%B7%B2%E7%BB%8F%E5%A4%B1%E6%95%88)

这个应该属于引用批注吧？感觉不是链接跳转，应该是书籍页脚加的一段详细解释说明。链接跳转(新开页面）感觉意义不大。我在看第十三章函数式编程 也遇到了
[第十三章 函数式编程](https://lingcoder.github.io/OnJava8/#/%E5%8A%9F%E8%83%BD%E7%B2%98%E8%B4%B4%E5%9C%A8%E4%B8%80%E8%B5%B7%E7%9A%84%E6%96%B9%E6%B3%95%E7%9A%84%E7%A1%AE%E6%9C%89%E7%82%B9%E4%B8%8E%E4%BC%97%E4%B8%8D%E5%90%8C%EF%BC%8C%E4%BD%86%E5%AE%83%E4%BB%8D%E4%B8%8D%E5%A4%B1%E4%B8%BA%E4%B8%80%E4%B8%AA%E5%BA%93%E3%80%82)

**Comment by teartao** [comment]
> 第三章，万物皆对象，数据存储（[https://github.com/LingCoder/OnJava8/blob/master/docs/book/03-Objects-Everywhere.md#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8）寄存器一段中，紧接“位于CPU内部”的"^2"所指向的链接已经失效](https://github.com/LingCoder/OnJava8/blob/master/docs/book/03-Objects-Everywhere.md#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8%EF%BC%89%E5%AF%84%E5%AD%98%E5%99%A8%E4%B8%80%E6%AE%B5%E4%B8%AD%EF%BC%8C%E7%B4%A7%E6%8E%A5%E2%80%9C%E4%BD%8D%E4%BA%8ECPU%E5%86%85%E9%83%A8%E2%80%9D%E7%9A%84%22%5E2%22%E6%89%80%E6%8C%87%E5%90%91%E7%9A%84%E9%93%BE%E6%8E%A5%E5%B7%B2%E7%BB%8F%E5%A4%B1%E6%95%88)

我仔细看了下。这个标注在网页是支持预览的，但是不能点开(因为并没有指向具体页面)。
如果到了PDF或者书(没有箭头预览形式)，就没办法点击预览。
唯一方法是到章节末尾 查看标注说明。

于是，我检查了章末，目前还没有这段翻译。

**Comment by LingCoder** [comment]
gihub不支持标准markdwon脚注。所有现在涉及脚注的显示是有点问题。但是项目下载到本地使用markdwon阅读器跳转是没问题的。我也还没想到两全其美的方法。不是太想在markdwon里加太多html标签
