### ISSUE TITLE
增强阅读体验

### ISSUE THREAD

**Issue by shangxiaomi** [LingCoder/OnJava8#450]
在阅读某一章时
如果想切换另一个章节，只能点 On Java8标题回到主页，希望能增加页内切换章节的功能

**Comment by freelancer10** [comment]
同感，支持一下

**Comment by LingCoder** [comment]
研究中！！

**Comment by JerryQiang** [comment]
> 研究中！！

有个简单的想法，类似于阅读小说
可以在每个章节加个**上一章**和**下一章**访问链接

**Comment by ruiwenfan** [comment]
确实，希望可以找个办法解决下
