### ISSUE TITLE
翻译错误：第十一章 内部类

### ISSUE THREAD

**Issue by ZhuXilin1997** [LingCoder/OnJava8#456]
###  申请翻译/校对

  * 校对

### 具体章节/标题

* 第十一章
  * 嵌套类
    * 从多层嵌套类中访问外部类的成员

_原文是：Reaching Outward from a Multiply Nested Class_

**应译为**
* 第十一章
  * 嵌套类
    * 从外部类访问多层嵌套类的成员

**Comment by sjsdfg** [comment]
= =  reach A from B 。 就是从 B 访问 A 啊

你这个翻译没懂

**Comment by ZhuXilin1997** [comment]
Ops，我这里脑子短路了，你说的对，就是从B访问A。
