### ISSUE TITLE
第十六章代码校验

### ISSUE THREAD

**Issue by KZsp** [LingCoder/OnJava8#472]
结尾的鲁棒性建议改成健壮性
https://github.com/LingCoder/OnJava8/blob/master/docs/book/16-Validating-Your-Code.md#%E6%9C%AC%E7%AB%A0%E5%B0%8F%E7%BB%93

**Comment by sjsdfg** [comment]
提 PR。并且这个要改的话要全文章一起改。

术语要统一

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
