### ISSUE TITLE
翻译不太友善

### ISSUE THREAD

**Issue by huixionghexiyi** [LingCoder/OnJava8#474]
你好，

首先，这本在线书做得很棒，内容非常丰富，涉及到了**Java8**的各个方面。是我见过的为数不多的不错的开源图书。

但是请允许我**吐槽**一下：

很多内容的翻译，看起来像机器翻译的。因为这并不符合我所理解的中文表达方式。
比如：
![image](https://user-images.githubusercontent.com/30774244/84361152-cba6c000-abfd-11ea-9953-6b6317690670.png)
[原文位置](https://lingcoder.github.io/OnJava8/#/book/24-Concurrent-Programming?id=%e5%b9%b6%e5%8f%91%e7%9a%84%e6%96%b0%e5%ae%9a%e4%b9%89)
- 序号1：意思可能想说这个定义的内容很**宽泛**或者**很广**。
- 序号2：我确实看不太明白其中的含义。

请原谅我的无礼，我的上帝。

**Comment by sjsdfg** [comment]
贴原文。 
提 PR 。

开源摆在这里就是接受大家审阅和修改的

**Comment by mintAqrua** [comment]
本来就是机翻的

**Comment by sjsdfg** [comment]
> 本来就是机翻的

觉得不好就提 PR ，不希望又遇到一个只会放嘴炮的人

**Comment by shajiquan** [comment]
> > @mintAqrua 本来就是机翻的
> 
>  @sjsdfg 觉得不好就提 PR ，不希望又遇到一个只会放嘴炮的人   

如果要参与讨论就必须PR，会不会阻了一些潜在的贡献者和参与者？

楼主这个帖子除了标题中的『友善』略感措辞欠妥，其余都是在认真、礼貌地讨论问题。就事论事来说，我并不认为是嘴炮。 

大家觉得呢？

祝大家都好。

**Comment by sjsdfg** [comment]
> > > @mintAqrua 本来就是机翻的
> > 
> > 
> > @sjsdfg 觉得不好就提 PR ，不希望又遇到一个只会放嘴炮的人
> 
> 如果要参与讨论就必须PR，会不会阻了一些潜在的贡献者和参与者？
> 
> 楼主这个帖子除了标题中的『友善』略感措辞欠妥，其余都是在认真、礼貌地讨论问题。就事论事来说，我并不认为是嘴炮。 
> 
> 大家觉得呢？
> 
> 祝大家都好。

看好我在回复谁。

另外一个这种只会下定论。连发现问题只会想解决问题的想法和思路都没有的人。我见一个喷一个。

说的跟我们开源项目赚他钱、还是欠他钱一样

**Comment by shajiquan** [comment]
> > > > @mintAqrua 本来就是机翻的
> > > 
> > > 
> > > @sjsdfg 觉得不好就提 PR ，不希望又遇到一个只会放嘴炮的人
> > 
> > 
> > 如果要参与讨论就必须PR，会不会阻了一些潜在的贡献者和参与者？
> > 楼主这个帖子除了标题中的『友善』略感措辞欠妥，其余都是在认真、礼貌地讨论问题。就事论事来说，我并不认为是嘴炮。 > 
> > 大家觉得呢？
> > 祝大家都好。
> 
> 看好我在回复谁。
> 
> 另外一个这种只会下定论。连解决问题的想法和思路都没有的人。我见一个喷一个。
> 
> 说的跟我们开源项目赚他钱、还是欠他钱一样

@sjsdfg 没问题，你说的对，爱喷你就多喷点，及时行乐，不想行乐时就直接关闭这个 repo 的 issue 功能。

**Comment by sjsdfg** [comment]
> > > > > @mintAqrua 本来就是机翻的
> > > > 
> > > > 
> > > > @sjsdfg 觉得不好就提 PR ，不希望又遇到一个只会放嘴炮的人
> > > 
> > > 
> > > 如果要参与讨论就必须PR，会不会阻了一些潜在的贡献者和参与者？
> > > 楼主这个帖子除了标题中的『友善』略感措辞欠妥，其余都是在认真、礼貌地讨论问题。就事论事来说，我并不认为是嘴炮。 > > >
> > > 大家觉得呢？
> > > 祝大家都好。
> > 
> > 
> > 看好我在回复谁。
> > 另外一个这种只会下定论。连解决问题的想法和思路都没有的人。我见一个喷一个。
> > 说的跟我们开源项目赚他钱、还是欠他钱一样
> 
> @sjsdfg 没问题，你说的对，爱喷你就多喷点，及时行乐，不想行乐时就直接关闭这个 repo 的 issue 功能。

看不惯就憋着。
