### ISSUE TITLE
gitbook epub报错

### ISSUE THREAD

**Issue by tangzhentao** [LingCoder/OnJava8#475]
gitbook epub报错如下
```shell
info: 16 plugins are installed 
info: 15 explicitly listed 
info: loading plugin "splitter"... OK 
info: loading plugin "edit-link"... OK 
info: loading plugin "search-pro"... OK 
info: loading plugin "emphasize"... OK 
info: loading plugin "toggle-chapters"... OK 
info: loading plugin "katex"... OK 
info: loading plugin "mermaid-gb3"... OK 
info: loading plugin "advanced-emoji"... OK 
info: loading plugin "include-codeblock"... 
warn: ace features disabled (`gitbook-plugin-ace` required)
OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 46 pages 
info: found 1797 asset files 
warn: "options" property is deprecated, use config.get(key) instead 
error: error while generating page "README.md": 

Error: connect ECONNREFUSED 0.0.0.0:443
```

**Comment by zhOrange** [comment]
同样的问题,请问解决了么?

**Comment by tangzhentao** [comment]
> 同样的问题,请问解决了么?

还没有，没找到解决方法，这里也没得到回复。

**Comment by zhOrange** [comment]
> > 同样的问题,请问解决了么?
> 
> 还没有，没找到解决方法，这里也没得到回复。

我今天解决了.
问题:
      SUMMARY.md文档目录设置的问题;
解决方式:
     我试了几次,发现把 SUMMARY.md中,前面的"译者的话"和"封面"两个标题删掉,
     重新执行gitbook epub,就能成功生成了.

仅做参考,希望可以帮到你.

**Comment by tangzhentao** [comment]
> > > 同样的问题,请问解决了么?
> > 
> > 
> > 还没有，没找到解决方法，这里也没得到回复。
> 
> 我今天解决了.
> 问题:
> SUMMARY.md文档目录设置的问题;
> 解决方式:
> 我试了几次,发现把 SUMMARY.md中,前面的"译者的话"和"封面"两个标题删掉,
> 重新执行gitbook epub,就能成功生成了.
> 
> 仅做参考,希望可以帮到你.

多谢分享！
我把 `SUMMARY.md`中,前面的`译者的话`和`封面`两个标题删掉后，
在`./OnJava8`目录下，执行`gitbook epub`后，还是报和之前一样的错误。

你看我下面的修改和你做的修改一样吗？
`原文`
```
# Summary

* [Introduction](README.md)
* [译者的话](docs/README.md)
* [封面](docs/book/00-On-Java-8.md)
* [前言](docs/book/00-Preface.md)
    * [教学目标](docs/book/00-Preface.md#教学目标)
...
```

`修改后`
```
# Summary

* [Introduction](README.md)
* [前言](docs/book/00-Preface.md)
    * [教学目标](docs/book/00-Preface.md#教学目标)
...
```

**补充**
我在做修改前，先更新了仓库。

**Comment by zhOrange** [comment]
> > > > 同样的问题,请问解决了么?
> > > 
> > > 
> > > 还没有，没找到解决方法，这里也没得到回复。
> > 
> > 
> > 我今天解决了.
> > 问题:
> > SUMMARY.md文档目录设置的问题;
> > 解决方式:
> > 我试了几次,发现把 SUMMARY.md中,前面的"译者的话"和"封面"两个标题删掉,
> > 重新执行gitbook epub,就能成功生成了.
> > 仅做参考,希望可以帮到你.
> 
> 多谢分享！
> 我把 `SUMMARY.md`中,前面的`译者的话`和`封面`两个标题删掉后，
> 在`./OnJava8`目录下，执行`gitbook epub`后，还是报和之前一样的错误。
> 
> 你看我下面的修改和你做的修改一样吗？
> `原文`
> 
> ```
> # Summary
> 
> * [Introduction](README.md)
> * [译者的话](docs/README.md)
> * [封面](docs/book/00-On-Java-8.md)
> * [前言](docs/book/00-Preface.md)
>     * [教学目标](docs/book/00-Preface.md#教学目标)
> ...
> ```
> 
> `修改后`
> 
> ```
> # Summary
> 
> * [Introduction](README.md)
> * [前言](docs/book/00-Preface.md)
>     * [教学目标](docs/book/00-Preface.md#教学目标)
> ...
> ```
> 
> **补充**
> 我在做修改前，先更新了仓库。

昨天在Ubuntu下操作的，我win10上一直装不上gitbook环境。现在系统盘不在边上，晚上给你回复吧。
稍微提供一个思路，你可以先试试。
（回复的时候忘了说了，我的README.md中也删减了一些内容，不过我当时以为没有关系就没在回复中提到。）
1、先把原工程git clone到本地；
2、在根目录下，找到README.md和SUMMARY.md，重命名为README.md.bak和SUMMARY.md.bak；
3、在当前目录下执行 gitbook init，成功的话，会重新生成上述两个文件；
4、这时候，先试试gitbook epub或者gitbook pdf看能不能成功（我这步是成功的）；
5、然后，先把README.md原来的内容（我没有copy全部，删减了一些），copy到新的文件中，再生成1次；
6、然后，再把SUMMARY.md原来的内容，copy到新的文件中，再生成1次（我就是在这部分出的错）；
7、出错的话，就控制变量法，先copy前一行，试一下，然后再copy后几行，再试一下（还是报错的话，试着把空行删了试试）；
8、我是试了几次后，发现是前面说的两个地方出的问题，删除那两个标题就可以了，你可以参考以下。

**Comment by tangzhentao** [comment]
> > > > > 同样的问题,请问解决了么?
> > > > 
> > > > 
> > > > 还没有，没找到解决方法，这里也没得到回复。
> > > 
> > > 
> > > 我今天解决了.
> > > 问题:
> > > SUMMARY.md文档目录设置的问题;
> > > 解决方式:
> > > 我试了几次,发现把 SUMMARY.md中,前面的"译者的话"和"封面"两个标题删掉,
> > > 重新执行gitbook epub,就能成功生成了.
> > > 仅做参考,希望可以帮到你.
> > 
> > 
> > 多谢分享！
> > 我把 `SUMMARY.md`中,前面的`译者的话`和`封面`两个标题删掉后，
> > 在`./OnJava8`目录下，执行`gitbook epub`后，还是报和之前一样的错误。
> > 你看我下面的修改和你做的修改一样吗？
> > `原文`
> > ```
> > # Summary
> > 
> > * [Introduction](README.md)
> > * [译者的话](docs/README.md)
> > * [封面](docs/book/00-On-Java-8.md)
> > * [前言](docs/book/00-Preface.md)
> >     * [教学目标](docs/book/00-Preface.md#教学目标)
> > ...
> > ```
> > 
> > 
> > `修改后`
> > ```
> > # Summary
> > 
> > * [Introduction](README.md)
> > * [前言](docs/book/00-Preface.md)
> >     * [教学目标](docs/book/00-Preface.md#教学目标)
> > ...
> > ```
> > 
> > 
> > **补充**
> > 我在做修改前，先更新了仓库。
> 
> 昨天在Ubuntu下操作的，我win10上一直装不上gitbook环境。现在系统盘不在边上，晚上给你回复吧。
> 稍微提供一个思路，你可以先试试。
> （回复的时候忘了说了，我的README.md中也删减了一些内容，不过我当时以为没有关系就没在回复中提到。）
> 1、先把原工程git clone到本地；
> 2、在根目录下，找到README.md和SUMMARY.md，重命名为README.md.bak和SUMMARY.md.bak；
> 3、在当前目录下执行 gitbook init，成功的话，会重新生成上述两个文件；
> 4、这时候，先试试gitbook epub或者gitbook pdf看能不能成功（我这步是成功的）；
> 5、然后，先把README.md原来的内容（我没有copy全部，删减了一些），copy到新的文件中，再生成1次；
> 6、然后，再把SUMMARY.md原来的内容，copy到新的文件中，再生成1次（我就是在这部分出的错）；
> 7、出错的话，就控制变量法，先copy前一行，试一下，然后再copy后几行，再试一下（还是报错的话，试着把空行删了试试）；
> 8、我是试了几次后，发现是前面说的两个地方出的问题，删除那两个标题就可以了，你可以参考以下。

感谢回复，最近加班有点多，有时间了我好好试试。
在此之前，能把你生成的epub发我一份吗，在我搞定之前先看你的epub。
1216880961@qq.com

**Comment by zhOrange** [comment]
> > > > > > 同样的问题,请问解决了么?
> > > > > 
> > > > > 
> > > > > 还没有，没找到解决方法，这里也没得到回复。
> > > > 
> > > > 
> > > > 我今天解决了.
> > > > 问题:
> > > > SUMMARY.md文档目录设置的问题;
> > > > 解决方式:
> > > > 我试了几次,发现把 SUMMARY.md中,前面的"译者的话"和"封面"两个标题删掉,
> > > > 重新执行gitbook epub,就能成功生成了.
> > > > 仅做参考,希望可以帮到你.
> > > 
> > > 
> > > 多谢分享！
> > > 我把 `SUMMARY.md`中,前面的`译者的话`和`封面`两个标题删掉后，
> > > 在`./OnJava8`目录下，执行`gitbook epub`后，还是报和之前一样的错误。
> > > 你看我下面的修改和你做的修改一样吗？
> > > `原文`
> > > ```
> > > # Summary
> > > 
> > > * [Introduction](README.md)
> > > * [译者的话](docs/README.md)
> > > * [封面](docs/book/00-On-Java-8.md)
> > > * [前言](docs/book/00-Preface.md)
> > >     * [教学目标](docs/book/00-Preface.md#教学目标)
> > > ...
> > > ```
> > > 
> > > 
> > > `修改后`
> > > ```
> > > # Summary
> > > 
> > > * [Introduction](README.md)
> > > * [前言](docs/book/00-Preface.md)
> > >     * [教学目标](docs/book/00-Preface.md#教学目标)
> > > ...
> > > ```
> > > 
> > > 
> > > **补充**
> > > 我在做修改前，先更新了仓库。
> > 
> > 
> > 昨天在Ubuntu下操作的，我win10上一直装不上gitbook环境。现在系统盘不在边上，晚上给你回复吧。
> > 稍微提供一个思路，你可以先试试。
> > （回复的时候忘了说了，我的README.md中也删减了一些内容，不过我当时以为没有关系就没在回复中提到。）
> > 1、先把原工程git clone到本地；
> > 2、在根目录下，找到README.md和SUMMARY.md，重命名为README.md.bak和SUMMARY.md.bak；
> > 3、在当前目录下执行 gitbook init，成功的话，会重新生成上述两个文件；
> > 4、这时候，先试试gitbook epub或者gitbook pdf看能不能成功（我这步是成功的）；
> > 5、然后，先把README.md原来的内容（我没有copy全部，删减了一些），copy到新的文件中，再生成1次；
> > 6、然后，再把SUMMARY.md原来的内容，copy到新的文件中，再生成1次（我就是在这部分出的错）；
> > 7、出错的话，就控制变量法，先copy前一行，试一下，然后再copy后几行，再试一下（还是报错的话，试着把空行删了试试）；
> > 8、我是试了几次后，发现是前面说的两个地方出的问题，删除那两个标题就可以了，你可以参考以下。
> 
> 感谢回复，最近加班有点多，有时间了我好好试试。
> 在此之前，能把你生成的epub发我一份吗，在我搞定之前先看你的epub。
> [1216880961@qq.com](mailto:1216880961@qq.com)

已发送.
对比了你的summary文件,我的和你的一样的,你再找找是哪的问题吧,应该是某一条标题后面的文件连接没有找到.虽然我的文档确实有,但不明白为啥没有找到,把那两个删除了就通过了.
