### ISSUE TITLE
集合这一章节的一个链接错误问题

### ISSUE THREAD

**Issue by xiguazhiPrince** [LingCoder/OnJava8#491]
这个章节https://lingcoder.github.io/OnJava8/#/book/12-Collections

`稍后，在[附录：集合主题](https://lingcoder.github.io/OnJava8/#/)中，还将学习到其余的那些集合和相关功能，以及如何使用它们的更多详细信息。`

附录：集合主题的链接链向错误了, 链接到了主页, 没有链接到附录那一章

**Comment by sjsdfg** [comment]
来个 PR 吧，修改之后我合进去
