### ISSUE TITLE
没有版权问题么？

### ISSUE THREAD

**Issue by sisishiliu** [LingCoder/OnJava8#499]

**Comment by ijrou** [comment]
其并没有做商业用途，如果觉得版权有点问题，建议购买正版支持作者：
https://play.google.com/store/books/details?id=p4ytDgAAQBAJ

**Comment by ControlByDestiny** [comment]
@sisishiliu 
去看看翻译的译者什么水平
[链接](https://github.com/LingCoder/OnJava8/issues/601)

**Comment by sjsdfg** [comment]
> @sisishiliu 
> 去看看翻译的译者什么水平
> [链接](https://github.com/LingCoder/OnJava8/issues/601)

愿意标榜你的二逼我可以挂到知乎上好好看看。

我回答你的问题你就只会无视

就这智商，滚吧

**Comment by sjsdfg** [comment]
> @sisishiliu 
> 去看看翻译的译者什么水平
> [链接](https://github.com/LingCoder/OnJava8/issues/601)

只会扣帽子的傻逼，我想请教请教你。你对这个生态付出什么了，不如给我一个 on java  8 的付费截图？

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
