### ISSUE TITLE
翻译有点不对意

### ISSUE THREAD

**Issue by ChelinTsien** [LingCoder/OnJava8#500]
第十三章 --> 柯里化和部分求值 ：

原文：The goal of currying is to be able to create a new function by providing a single argument, so you now have an “argumented function” and the remaining “free argument.” In effect, you start with a two-argument function and end up with a one-argument function.
译文：柯里化的目的是能够通过提供一个参数来创建一个新函数,所以现在有了一个“带参函数”和剩下的“无参函数” 。实际上,你从一个双参数函数开始,最后得到一个单参数函数。

the remaining “free argument.” 翻译成：剩下的“无参函数” 有点不对意的感觉

**Comment by sjsdfg** [comment]
给出自己的修改意见

**Comment by ChelinTsien** [comment]
```
// 柯里化的函数:
Function<String, Function<String, String>> sum =
a -> b -> a + b; // [1]
System.out.println(uncurried("Hi ", "Ho"));
Function<String, String>
hi = sum.apply("Hi "); // [2]
System.out.println(hi.apply("Ho"));
```
所以柯里化是 产生一个 Function （hi）  和剩下的参数，并不是 “无参函数” , 所以可以直译为 “自由参数”

**Comment by sjsdfg** [comment]
提 PR 吧，把原文的英文单词缀在后面。避免后面人看到自由参数一脸蒙蔽

告诉他原文就是 （free argumnet）
