### ISSUE TITLE
24章： 代码块newlong[SZ+1] 应该是new long[SZ+1]。中间多一个空格

### ISSUE THREAD

**Issue by Jamps-Yu** [LingCoder/OnJava8#501]
###  申请校对

  * 校对

### 具体章节/标题

* 24章
  * 并行流
原文第三个代码块中的“newlong[SZ+1]” 应该是"new long[SZ+1]"。中间应该多一个空格

**Comment by sjsdfg** [comment]
这种直接 提 PR 就好

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
