### ISSUE TITLE
第10章接口--接口适配第一句的书写问题

### ISSUE THREAD

**Issue by yanxueer** [LingCoder/OnJava8#508]
###  申请翻译/校对

  * 翻译
接口最吸引人的原因之一是相同的接口可以有多个实现。在简单情况下体现在一个方法接受接口作为参数，**“该接口的实现和传递对象给方法则交由你来做”**。
### 第10章接口/接口适配

上述加粗部分为病句。

* 示例
  * **“该接口的实现和传递对象则交给方法来做”**
  * 或者参考第四版中文书籍 **“该接口的实现和传递对象则取决于方法的使用者”**

第一次提交issue 如有问题还望谅解，诸君加油！！！！

**Comment by sjsdfg** [comment]
提 pr
