### ISSUE TITLE
【第十章 接口】-【接口创建】-【接口中的静态方法】

### ISSUE THREAD

**Issue by AlanMeng** [LingCoder/OnJava8#521]
【这里展示了创建 Operations 的不同方式：一个外部类(Bing)，一个匿名类，一个方法引用和 lambda 表达式——毫无疑问用在这里是最好的解决方法。】：
实际上都是标准的外部类创建方式？看了原文，似乎也是这样写的，是描述和示例代码不相符？

**Comment by sjsdfg** [comment]
把上下文补全。

译文的内容

原文的内容


「书中也不是全对，可能有错误」

**Comment by AlanMeng** [comment]
译文：
这里展示了创建 Operations 的不同方式：一个外部类(Bing)，一个匿名类，一个方法引用和 lambda 表达式——毫无疑问用在这里是最好的解决方法。

原文：
Here you see the different ways to create Operations: an external class (Bing), an anonymous class, a method reference, and lambda expressions—which certainly appear to be the nicest solution here.

原文代码：
// interfaces/Machine.java
import java.util.*;
import onjava.Operations;

class Bing implements Operations {
  public void execute() {
    Operations.show("Bing");
  }
}

class Crack implements Operations {
  public void execute() {
    Operations.show("Crack");
  }
}

class Twist implements Operations {
  public void execute() {
    Operations.show("Twist");
  }
}

public class Machine {
  public static void main(String[] args) {
    Operations.runOps(
      new Bing(), new Crack(), new Twist());
  }
}
/* Output:
Bing
Crack
Twist
*/

单纯翻译没有问题，但是代码和说明似乎对不上，不知道是不是我的理解问题。
![onJava8](https://user-images.githubusercontent.com/15899912/88635859-c4bf0880-d0ea-11ea-8153-b35f4aeffa78.png)

**Comment by sjsdfg** [comment]
嗯，全都是展示的外部类使用方式了。是有问题

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
