### ISSUE TITLE
有一个错别字

### ISSUE THREAD

**Issue by yanghaoGH** [LingCoder/OnJava8#529]
在Appendix-IO-Streams.md这个文档里。在【这里我只会提供这些类的概述，并假定你会使用 JDK 文档来获取它们的详细信息（比如某个类的所以方法的详细列表）】这句话中【所以】或许是【所有】

**Comment by sjsdfg** [comment]
直接提 PR

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
