### ISSUE TITLE
第六章 PassingThis.java 代码出错

### ISSUE THREAD

**Issue by FDgithub123** [LingCoder/OnJava8#532]
中文翻译给Apple和Peeler两个类都添加了public前缀，然而java只允许一个文件有一个public class，
果然实际运行时会报错，去除后代码运行正常，并且本书的英文原版这两处并没有public，应该是译者不小心误添加了。
这里附上更正后的代码

`// housekeeping/PassingThis.java

class Person {
    public void eat(Apple apple) {
        Apple peeled = apple.getPeeled();
        System.out.println("Yummy");
    }
}

class Peeler {
    static Apple peel(Apple apple) {
        // ... remove peel
        return apple; // Peeled
    }
}

class Apple {
    Apple getPeeled() {
        return Peeler.peel(this);
    }
}

public class PassingThis {
    public static void main(String[] args) {
        new Person().eat(new Apple());
    }
}
`

**Comment by sjsdfg** [comment]
直接提PR

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
