### ISSUE TITLE
第十三章 函数式编程 有个错的单词

### ISSUE THREAD

**Issue by Decandy-star** [LingCoder/OnJava8#535]
![SKR280 `I IX2)K~TX)O8KC](https://user-images.githubusercontent.com/59561865/89513680-73f49180-d807-11ea-8e51-0de11dbd3f3e.png)
应该是不包含foo

**Comment by sjsdfg** [comment]
提 PR

**Comment by Decandy-star** [comment]
> 提 PR
请问下pr是什么？新人不大懂

**Comment by sjsdfg** [comment]
https://github.com/LingCoder/OnJava8/blob/master/CONTRIBUTING.md

![image](https://user-images.githubusercontent.com/8037152/89517479-5118ac00-d80c-11ea-9901-14cb93e785eb.png)
