### ISSUE TITLE
一段时间没看，目录怎么变成这样了

### ISSUE THREAD

**Issue by Decandy-star** [LingCoder/OnJava8#550]
《On Java 8》中文版
译者的话
">
译者的话
封面
">
封面
前言
">
前言
简介
">
简介
第一章 对象的概念
">
第一章 对象的概念
第二章 安装Java和本书用例
">
第二章 安装Java和本书用例
第三章 万物皆对象
">
第三章 万物皆对象
第四章 运算符
">
第四章 运算符
第五章 控制流
">
第五章 控制流
第六章 初始化和清理
">
第六章 初始化和清理
第七章 封装
">
第七章 封装
第八章 复用
">
第八章 复用
第九章 多态
">
第九章 多态
第十章 接口
">
第十章 接口

不能截图，我就把目录复制了下文字，gitee和github的网页版都是这样

**Comment by LeonTheProfessional** [comment]
是的，我这里也是这样了

**Comment by Arther1228** [comment]
我也是这样

**Comment by zhanglintc** [comment]
以前长啥样不知道, 至少目前 github 这边看起来还可以了  https://github.com/LingCoder/OnJava8/commit/12b5813041df2d7bad7f206cae89d29065e05cec 👍
