### ISSUE TITLE
通顺

### ISSUE THREAD

**Issue by long-jie** [LingCoder/OnJava8#551]
在这个例子中，类型／类的名称是 Light，可向 Light 对象发出的请求包括打开 on、关闭 off、变得更明亮 brighten 或者变得更暗淡 dim。**通过声明一个引用，如 lt 和 new 关键字**，我们创建了一个 Light 类型的对象，再用等号将其赋给引用。

->

在这个例子中，类型／类的名称是 Light，可向 Light 对象发出的请求包括打开 on、关闭 off、变得更明亮 brighten 或者变得更暗淡 dim。**通过声明一个引用lt 和 new 关键字**，我们创建了一个 Light 类型的对象，再用等号将其赋给引用。

**Comment by sjsdfg** [comment]
直接提 pr
