### ISSUE TITLE
严谨一点的话，并发编程应改为并行编程

### ISSUE THREAD

**Issue by PureDeer** [LingCoder/OnJava8#553]
原文第十三章，前言部分倒数第三段中，“...parallel programming (when parts of your program are running simultaneously on multiple processors)”，严谨一点的话，concurrency programming(并发) 和 parallelism programming(并行)应该是两个不同的概念，而原文括号后面的定义恰是并行编程的定义；是否应该修改？

**Comment by sjsdfg** [comment]
提 PR 吧，以原文为主

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
