### ISSUE TITLE
第二十四章  并发编程 

### ISSUE THREAD

**Issue by amyxin** [LingCoder/OnJava8#563]
### 第二十四章  并发编程   **创建和运行任务** 
> 示例代码1  id声明    final和int关键字中间少了空格
![QQ图片20200905224832](https://user-images.githubusercontent.com/15379166/92307559-f4a2db00-efc9-11ea-8058-613c77f534e7.png)

**Comment by sjsdfg** [comment]
直接提交 PR 吧

**Comment by amyxin** [comment]
> 直接提交 PR 吧

好的，已提交
