### ISSUE TITLE
第十四章的翻译有点泪目

### ISSUE THREAD

**Issue by robertzee** [LingCoder/OnJava8#589]
举例来说
id=optional类

原文（加黑字段）：
Before we can look at terminal operations, we must consider what happens if you ask for an object in a stream and there’s nothing there. **We like to connect up our streams for the “happy path” and assume nothing will break**. Putting a null in a stream is a good way to break it. Is there some kind of object we can use that will act **as a holder for a stream element**, but can also kindly tell us (that is, no exceptions) if the element we’re looking for isn’t there?

翻译：
1. 我们喜欢为了“happy path”而将流连接起来
评论：这里的happy path应翻译成：我们希望将所有的steam对象轻松地连接起来，而不会出现什么异常。
happy path应该作为副词，形容操作本身，而不是作为连接的节点。

2. 可作为流元素的持有者
评论：Holder应该作为容器来解释更为妥当。

**Comment by sjsdfg** [comment]
直接提 pr

**Comment by jangbeyond** [comment]
我试着改了一下。。。 #595

**Comment by a524631266** [comment]
用null值来结束流，这样的观点我还是首次get

**Comment by sjsdfg** [comment]
> 用null值来结束流，这样的观点我还是首次get

这种神奇的观点应该就是想触发 RuntimeException
