### ISSUE TITLE
版权，生态，你考虑过吗？

### ISSUE THREAD

**Issue by ControlByDestiny** [LingCoder/OnJava8#601]
1.你获取到原作者的中文译版的授权了？
2.原作者是否同意你对本书进行中文翻译版的开源？
3.有没有考虑过对整个外国技术文档翻译行业的影响？

附：
想开源是好事，但要有基本的原则

**Comment by sjsdfg** [comment]
嘴炮，你做啥了？

**Comment by sjsdfg** [comment]
还文档翻译行业。搞笑

**Comment by ControlByDestiny** [comment]
你是真的憨批，知道尊重原创吗

**Comment by ControlByDestiny** [comment]
等起诉的，别BB

**Comment by sjsdfg** [comment]
> 你是真的憨批，知道尊重原创吗

嘴炮就知道说这两句。不会干别的，毕竟嘴炮。

因为这本书的高 star ，人邮那边才看到这本书的市场价值，去联系作者那边做官方引入了，懂么？
你做了什么？
憨批

**Comment by sjsdfg** [comment]
> 你是真的憨批，知道尊重原创吗

除了放两句嘴炮，然后你看着盗版书过来心口不一的说两句风凉话，标榜你的二逼？

**Comment by sjsdfg** [comment]
> 等起诉的，别BB

不服就举报。大不了我们关项目。
欠你们的？

**Comment by ControlByDestiny** [comment]
厉害。原来全国就您一个人能看懂英文版的。

**Comment by ControlByDestiny** [comment]
不好意思，你们项目我一个字都没看，床头一本亚马逊买的原版，需要我寄给你吗

**Comment by sjsdfg** [comment]
> 厉害。原来全国就您一个人能看懂英文版的。

就这智商真的堪忧。
不知道你哪里来的论据都能脑补得出只有我懂英文的结论

你这智商告别编程吧

**Comment by ControlByDestiny** [comment]
原来你是码农啊，那你看这本书有什么用呢？

**Comment by sjsdfg** [comment]
> 厉害。原来全国就您一个人能看懂英文版的。

跟你说 A 的问题 A 不回复然后说 B .

就你这种傻逼别回复了。

不服就去举报。反正人邮去接洽了，引子已经做够了。

自嗨的傻逼

**Comment by ControlByDestiny** [comment]
不对，码农看看还是有收益的。

**Comment by ControlByDestiny** [comment]
用惯了盗版软件，真的是觉得全世界都欠你的。

**Comment by sjsdfg** [comment]
> 用惯了盗版软件，真的是觉得全世界都欠你的。

果然是傻逼。前面的不回复抛出问题 C 。

你这种才是觉得世界都欠你的。傻逼。

你对这个生态做了什么，回复我了么？

**Comment by ControlByDestiny** [comment]
第一，没有一句话否定你们的付出。
第二，你们想翻译，想开源，是好事。
第三，你们在决定开源前，应获取原作者的授权。
第四，未获取到原作者的授权，就对本书的进行中文翻译并开源是违法的。
第五，人邮即使在帮你们联系，也是给你们擦屁股。违法已经是事实。

**Comment by ControlByDestiny** [comment]
> > 用惯了盗版软件，真的是觉得全世界都欠你的。
> 
> 果然是傻逼。前面的不回复抛出问题 C 。
> 
> 你这种才是觉得世界都欠你的。傻逼。
> 
> 你对这个生态做了什么，回复我了么？

你是什么东西？为什么要回复你？

**Comment by sjsdfg** [comment]
> 第一，没有一句话否定你们的付出。
> 第二，你们想翻译，想开源，是好事。
> 第三，你们在决定开源前，应获取原作者的授权。
> 第四，未获取到原作者的授权，就对本书的进行中文翻译并开源是违法的。
> 第五，人邮即使在帮你们联系，也是给你们擦屁股。违法已经是事实。

1. 上来就扣帽子就能这么圆，脑回路清奇
2. 话里话外看不出来
3. 原作者授权问 repo 主去，他联系过了
4. 商业性盈利违法，这书盈利了？你看书付钱了？
5. 脑回路之清奇你完全没看懂？ 这本书翻译有商业价值，能卖钱赚钱了了，人邮要自己拿版权自己搞。跟给我们擦屁股有毛关系？你逻辑真差

**Comment by sjsdfg** [comment]
> > > 用惯了盗版软件，真的是觉得全世界都欠你的。
> > 
> > 果然是傻逼。前面的不回复抛出问题 C 。
> > 
> > 你这种才是觉得世界都欠你的。傻逼。
> > 
> > 你对这个生态做了什么，回复我了么？
> 
> 你是什么东西？为什么要回复你？

哦，说的对。你是个傻逼。

是我试图跟傻逼交流，是我错了

**Comment by ControlByDestiny** [comment]
> > 用惯了盗版软件，真的是觉得全世界都欠你的。
> 
> 果然是傻逼。前面的不回复抛出问题 C 。
> 
> 你这种才是觉得世界都欠你的。傻逼。
> 
> 你对这个生态做了什么，回复我了么？

你这种满口脏话，不懂得尊重人，你配我回复吗？这就是你对外的形象？你这种水平，这种素质的人都能来翻译。对该项目另眼相看。

**Comment by sjsdfg** [comment]
> > > 用惯了盗版软件，真的是觉得全世界都欠你的。
> > 
> > 果然是傻逼。前面的不回复抛出问题 C 。
> > 
> > 你这种才是觉得世界都欠你的。傻逼。
> > 
> > 你对这个生态做了什么，回复我了么？
> 
> 你是什么东西？为什么要回复你？

毕竟我和傻逼不是同类

**Comment by sjsdfg** [comment]
> > > 用惯了盗版软件，真的是觉得全世界都欠你的。
> > 
> > 果然是傻逼。前面的不回复抛出问题 C 。
> > 
> > 你这种才是觉得世界都欠你的。傻逼。
> > 
> > 你对这个生态做了什么，回复我了么？
> 
> 你这种满口脏话，不懂得尊重人，你配我回复吗？这就是你对外的形象？你这种水平，这种素质的人都能来翻译。对该项目另眼相看。

Show me your code。
傻逼太多了，上来就扣帽子的不值得我好好交流

**Comment by sjsdfg** [comment]
> 不好意思，你们项目我一个字都没看，床头一本亚马逊买的原版，需要我寄给你吗

亚马逊原版。笑死我得了。

这本书只卖 google play 电子版ok。 

还亚马逊原版纸质版。你给我买的盗版么？

你寄给我吧，让我看看书籍首页上面就写的永远不出纸版书籍的书长什么样

**Comment by sjsdfg** [comment]
> 不好意思，你们项目我一个字都没看，床头一本亚马逊买的原版，需要我寄给你吗

这年头嘴炮门槛真低

https://www.amazon.com/s?k=on+java+8+bruce&sprefix=on+java+8&ref=nb_sb_ss_i_2_9

**Comment by sjsdfg** [comment]
> 原来你是码农啊，那你看这本书有什么用呢？

一边说码农看了才有用
一边吹自己买了个纸质版

麻烦你出来把脑子带上，什么时候说话能逻辑自洽了再说话。

你这不变相嘲讽你自己是码农？
还是你是更低级的码畜

**Comment by TinusgragLin** [comment]
哈哈哈哈，“床头一本亚马逊原版”，老哥你也太不专业了，撒谎前也最好google一下嘛。

**Comment by ControlByDestiny** [comment]
> 哈哈哈哈，“床头一本亚马逊原版”，老哥你也太不专业了，撒谎前也最好google一下嘛。

不重要，出于好心的提醒，没想到被个疯狗使劲咬

**Comment by ControlByDestiny** [comment]
手动@疯狗， @sjsdfg 出来咬人了
