### ISSUE TITLE
第十二章 集合中最后的译者附图有误

### ISSUE THREAD

**Issue by kaimeng110091** [LingCoder/OnJava8#610]
Iterator的子接口是ListIterator

**Comment by sjsdfg** [comment]
****
![image](https://user-images.githubusercontent.com/8037152/96869126-a4aca480-14a1-11eb-88f0-b258d781f56c.png)
所以是哪里错了？

**Comment by sjsdfg** [comment]
![image](https://user-images.githubusercontent.com/8037152/96869202-c574fa00-14a1-11eb-8836-4ad0b4799d6f.png)
哦，看到了。。这个附注的错了
