### ISSUE TITLE
第十章接口有语句逻辑不明

### ISSUE THREAD

**Issue by Kronsos** [LingCoder/OnJava8#611]
>记住，事实上的访问权限是“friendly”。你很快会看到接口自动将其方法指明为 public。事实上，接口只允许 public 方法，如果不加访问修饰符的话，接口的方法不是 friendly 而是 public。然而，抽象类允许每件事：

这句话有点逻辑不明，而且上下文也无法推出原义

**Comment by sjsdfg** [comment]
找原文上来一起提PR 改进

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
