### ISSUE TITLE
第十八章：字符串 / 创建正则表达式 / 第二个表格 / [abc[hij]]和[a-z&&[hij]]行

### ISSUE THREAD

**Issue by imtoam** [LingCoder/OnJava8#615]
第十八章：字符串 / 创建正则表达式 / 第二个表格 / 

1. [abc[hij]]行 
含义： _a、b、c、h、i、j中的任意字符（与`a_
问题：翻译语句不完整
2. [a-z&&[hij]]行 
含义：_任意h、i或j（交）_
问题：“（交）”语义晦涩难理解

**Comment by sjsdfg** [comment]
直接改了提 PR

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
