### ISSUE TITLE
第十一章 内部类/为什么需要内部类/内部类与控制框架 GreenhouseContrlos写错了

### ISSUE THREAD

**Issue by wutongsuimeng** [LingCoder/OnJava8#616]
## 第十一章 内部类/为什么需要内部类/内部类与控制框架
  “读者可能注意到了内部类是多么像多重继承：**Bell** 和 **Restart** 有 **Event** 的所有方法，并且似乎也拥有外部类 **GreenhouseContrlos** 的所有方法。”中的**GreenhouseContrlos**写错了，应该为**GreenhouseControls**的

**Comment by sjsdfg** [comment]
这种直接提 PR

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
