### ISSUE TITLE
写技术文章可以引用书中的段落吗

### ISSUE THREAD

**Issue by liguoyan123** [LingCoder/OnJava8#627]

**Comment by sjsdfg** [comment]
这种都没啥问题吧。

一般标明一下出处

**Comment by liguoyan123** [comment]
好的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LingCoder/OnJava8"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午5:05
收件人:&nbsp;"LingCoder/OnJava8"<OnJava8@noreply.github.com&gt;;
抄送:&nbsp;"想起你会笑ii"<190943540@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LingCoder/OnJava8] 写技术文章可以引用书中的段落吗 (#627)





 
这种都没啥问题吧。
 
一般标明一下出处
