### ISSUE TITLE
18章String format的一点疑问

### ISSUE THREAD

**Issue by akiratei** [LingCoder/OnJava8#628]
文中说：``从这个表可以看出，当需要改变字符串的内容时，String 类的方法都会返回一个新的 String 对象。同时，如果内容不改变，String 方法只是返回原始对象的一个引用而已。这可以节约存储空间以及避免额外的开销。``
但是：
```
String f1 = String.format("a:%s", "b");
String f2 = String.format("a:%s", "b");
System.out.println("f1 == f2: " + (f1 == f2));
System.out.println("f1.hashcode == f2.hashcode: " + (f1.hashCode() == f2.hashCode()));
System.out.println("f1 equals f2: " + (f1.equals(f2)));
```
结果：
```
f1 == f2: false
f1.hashcode == f2.hashcode: true
f1 equals f2: true
```
请教下，这种情况下引用并不相同。
最近在公司项目中发现一个方法中，在方法体内先根据ID使用String.format来初始化一个锁，然后使用synchronized代码块来加锁，有些疑问，不同线程调用时拿到的锁是一个吗？
示例：
```
public void demo(A a) {
       String lock = String.format("LOCK:%s",  a.getId());
        synchronized(lock) {
               // doing sth
        }
}
```

**Comment by sjsdfg** [comment]
不是同一个锁。。公司内的代码写的这么草率么

**Comment by sjsdfg** [comment]
![image](https://user-images.githubusercontent.com/8037152/101308150-24d96e80-3884-11eb-9ea8-a19e88c3f80d.png)
![Uploading image.png…]()

这种可以自己测一下，也可以多用用 IDE。 现在 IDEA 是很牛逼的

**Comment by sjsdfg** [comment]
![image](https://user-images.githubusercontent.com/8037152/101308959-13916180-3886-11eb-9db2-0aa71ac947c8.png)
