### ISSUE TITLE
第二十四章第二段有错别字

### ISSUE THREAD

**Issue by ClayGminx** [LingCoder/OnJava8#633]
现在，我们来到了陌生的并发世界。这样的结果一点都不奇怪，因为你原来信赖的一切都不再可靠。它可能有效，也可能无效。更可能得是，它在某些情况下会起作用，而在另一些情况下则不会。只有了解了这些情况，我们才能正确地行事。

第4句应是“更可能的是”。

**Comment by sjsdfg** [comment]
直接提 PR 就可以了
