### ISSUE TITLE
右移位运算符（>>>）有误

### ISSUE THREAD

**Issue by cawendy** [LingCoder/OnJava8#634]
我的测试结果与理论“Java 也添加了一种“不分正负”的右移位运算符（>>>），它使用了“零扩展”（zero extension）：无论正负，都在高位插入 0。”和“仅使用右值（rvalue）的 5 个低阶位”不相符；但我没发现其中的规律，可以看出与正负号相关；请重新审查；期待回复

测试代码如下：

测试一：
short s = -88;
System.out.println(Integer.toBinaryString(s));
s >>>= 10;
System.out.println(Integer.toBinaryString(s));
------------------------------结果-----------------------
11111111111111111111111110101000
11111111111111111111111111111111

测试二：
short s = 88;
System.out.println(Integer.toBinaryString(s));
s >>>= 10;
System.out.println(Integer.toBinaryString(s));
------------------------------结果-----------------------
1011000
0

**Comment by sjsdfg** [comment]
![image](https://user-images.githubusercontent.com/8037152/102859536-04eea100-4467-11eb-8d24-fb3fe11691ef.png)

看官方文档只支持 long 和 int。你用 short 做测试有问题
https://docs.oracle.com/javase/specs/jls/se15/html/jls-15.html#jls-15.19
