### ISSUE TITLE
前言-本书的组织第三段切片翻译有误

### ISSUE THREAD

**Issue by shoreyk** [LingCoder/OnJava8#635]
译文：“第四章描述了复合类型，从简单的数组、字典、切片到动态列表。”
原文：“ Chapter 4 describes composite types, that is, types built up from simpler ones using arrays, maps, structs, and slices, Go’s approach to dynamic lists.”

Go’s approach to dynamic lists是对斜体slices的解释，您翻译成了并列关系，望改正

**Comment by sjsdfg** [comment]
开源项目。直接提 PR

**Comment by shoreyk** [comment]
我不会翻译 我只知道错了 不好意思

**Comment by sjsdfg** [comment]
https://github.com/LingCoder/OnJava8/search?q=%E5%B9%B6%E5%88%97%E5%85%B3%E7%B3%BB&type=code

没找到你说的错误翻译的位置在哪。请明确指出
