### ISSUE TITLE
感觉也就那样。。。

### ISSUE THREAD

**Issue by Super-zhw** [LingCoder/OnJava8#640]
rt

**Comment by sjsdfg** [comment]
github 空白一片。你也就那样吧。
看着就菜

**Comment by sjsdfg** [comment]
https://blog.csdn.net/a145127
从博客上面能发现你更菜

**Comment by pushrbp** [comment]
就挺离谱的，特意发个issue来踩一踩。其实你要是觉得有翻译不够妥当的地方，发个pr可能会更好！

**Comment by lilingshan** [comment]
感觉牛逼啊

**Comment by TonySFU** [comment]
只能说这就是技校和科班出身的区别吧，不管你什么水平的看这本书都应该收获蛮大的。

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
