### ISSUE TITLE
错别字修改

### ISSUE THREAD

**Issue by marshallV** [LingCoder/OnJava8#652]
### 具体章节

* 附录:并发底层原理
  * 原子性
    * 经常反复提交-----中的“提交”为“提到”才对。

**Comment by LingCoder** [comment]
谢谢你的关注，因为版权原因，项目即将清空和归档。不再接受pr和处理翻译的issue

**Comment by LingCoder** [comment]
因版权原因，项目已清空归档。非常抱歉，感谢您的关注。有兴趣可以加群交流
