### ISSUE TITLE
一脸懵，转到图灵去，就搞成闭源了？？？

### ISSUE THREAD

**Issue by nian8** [LingCoder/OnJava8#653]

**Comment by sjsdfg** [comment]
1. 先弄明白，图灵去年拿下版权之后只有他是正版
2. 没有转不转的问题，图灵有自己挑选的译者。并没有采用社区版。并且我个人去参选译者已经落选了，对方译者在细节处理上更为优秀
3. 对方作为版权拥有方，要求我方闭源。有问题么？

**Comment by nian8** [comment]
原来如此。。。
