### ISSUE TITLE
你好，我正在读第六章，我建议一些术语采用英文原单词。翻译成中文很奇怪。比如这个自动装箱。

### ISSUE THREAD

**Issue by Tusen183** [LingCoder/OnJava8#656]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* 示例章节
  * 示例标题1
  * 示例标题2

**Comment by Tusen183** [comment]
> ## 我愿成为一名开源贡献者！
> ### 申请翻译/校对
> * 翻译
> 
> ### 具体章节/标题
> * 示例章节
>   
>   * 示例标题1
>   * 示例标题2

**Comment by usershu** [comment]
项目已经不维护了吧，真有心去留下的图灵链接看看，可以参加校对或者翻译
