### ISSUE TITLE
可以发一下电子版吗

### ISSUE THREAD

**Issue by beruhan** [LingCoder/OnJava8#7]

**Comment by LingCoder** [comment]
不好意思,最近好忙,我今天开始更起来.谢谢你的关注.我刚弄了个QQ群.你加进来721698221

**Comment by wizardforcel** [comment]
请执行 gitbook epub。

**Comment by sjsdfg** [comment]
本 issue 所提的应该是英文版本 pdf。
不要误以为是中文版本 pdf.
尚未翻译完成，初稿都没有，不会提供 pdf。
想要中文 pdf 的自己使用 gitbook 处理

**Comment by a471640241** [comment]
请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2   gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名  gitbook pdf 或者是其他格式都会报错,错误如下
![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)

**Comment by wizardforcel** [comment]
@a471640241 Gitbook 可能不方便处理 SVG。。。

**Comment by a471640241** [comment]
> > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> 
> 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。

我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你

**Comment by WallofWonder** [comment]
> > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > 
> > 
> > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> 
> 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你

能发给我一份吗

**Comment by a471640241** [comment]
> > > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > > 
> > > 
> > > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> > 
> > 
> > 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你
> 
> 能发给我一份吗

邮箱地址

**Comment by WallofWonder** [comment]
> > > > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > > > 
> > > > 
> > > > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> > > 
> > > 
> > > 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你
> > 
> > 
> > 能发给我一份吗
> 
> 邮箱地址

m13110683916@163.com 谢谢了🙏

**Comment by yinyy111** [comment]
> > > > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > > > 
> > > > 
> > > > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> > > 
> > > 
> > > 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你
> > 
> > 
> > 能发给我一份吗
> 
> 邮箱地址
13120228892@163.com也需要哦 谢谢啦🙏

**Comment by soyalu** [comment]
soyalu@outlook.com,能发我一份吗？谢谢！

**Comment by Victoryczz** [comment]
> > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > 
> > 
> > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> 
> 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你

球球求求求 发我一份中文的pdf  690028760@qq.com  谢谢

**Comment by afeihenmang** [comment]
> > > > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > > > 
> > > > 
> > > > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> > > 
> > > 
> > > 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你
> > 
> > 
> > 能发给我一份吗
> 
> 邮箱地址

你好，麻烦你发我一份，谢谢
744883037@qq.com
感谢🙏

**Comment by a7611818** [comment]
> > > > > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > > > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > > > > 
> > > > > 
> > > > > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> > > > 
> > > > 
> > > > 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你
> > > 
> > > 
> > > 能发给我一份吗
> > 
> > 
> > 邮箱地址
> 
> 你好，麻烦你发我一份，谢谢
> [744883037@qq.com](mailto:744883037@qq.com)
> 感谢🙏

869329190@qq.com
同求!感谢了

**Comment by anuger** [comment]
@a7611818 这是 https://github.com/LingCoder/OnJava8/commit/6dc8b720e3d8b58e7f1351b5bc5ce78d044cdba1 commit以前的pdf
[下载](http://106.54.187.105:8181/book.zip)

**Comment by flyzyh** [comment]
> @a7611818 这是 [6dc8b72](https://github.com/LingCoder/OnJava8/commit/6dc8b720e3d8b58e7f1351b5bc5ce78d044cdba1) commit以前的pdf
> [下载](http://106.54.187.105:8181/book.zip)

感谢感谢。我这也是gitbook转成pdf/epub的过程全部出错，多亏看到了这条回答。

**Comment by anuger** [comment]
@flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了

**Comment by anuger** [comment]
@flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了

**Comment by flyzyh** [comment]
> @flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了
> 
> > 已更新到 [7b80942](https://github.com/LingCoder/OnJava8/commit/7b8094287411818b64e35a75055c9f7272733dea)
> > [下载](http://106.54.187.105:8181/book.zip)

实在是太感谢了！
另外如果方便的话，希望能有epub或者mobi格式，这样电子设备看着舒服一点。

**Comment by anuger** [comment]
[mobi](http://106.54.187.105:8181/book.mobi)下载

**Comment by flyzyh** [comment]
> [mobi](http://106.54.187.105:8181/book.mobi)下载

咦？怎么下载不到了？是我来晚了吗。。。。。

**Comment by anuger** [comment]
> > [mobi](http://106.54.187.105:8181/book.mobi)下载
> 
> 咦？怎么下载不到了？是我来晚了吗。。。。。

不好意思哈,重启机器忘记起服务了,现在可以了 @flyzyh

**Comment by flyzyh** [comment]
> > > [mobi](http://106.54.187.105:8181/book.mobi)下载
> > 
> > 
> > 咦？怎么下载不到了？是我来晚了吗。。。。。
> 
> 不好意思哈,重启机器忘记起服务了,现在可以了 @flyzyh
下好了。真是太感谢了

**Comment by tinglucomputer** [comment]
> > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > 
> > 
> > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> 
> 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你

大佬，能发我一份吗? 2321894289@qq.com，不胜感激。

**Comment by cheng-shuai** [comment]
> @flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了
> 
> > 已更新到 [7b80942](https://github.com/LingCoder/OnJava8/commit/7b8094287411818b64e35a75055c9f7272733dea)
> > [下载](http://106.54.187.105:8181/book.zip)

非常感谢

**Comment by pobc** [comment]
请问，上面截图中的错误解决了吗？我也出现了这个错误

**Comment by lymansix** [comment]
感谢发电子版的兄弟，辛苦了

**Comment by zhOrange** [comment]
> @flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了
> 
> > 已更新到 [7b80942](https://github.com/LingCoder/OnJava8/commit/7b8094287411818b64e35a75055c9f7272733dea)
> > [下载](http://106.54.187.105:8181/book.zip)

大佬，新版的pdf又打不开了，可以重发一下么？

**Comment by zhOrange** [comment]
> > @flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了
> > > 已更新到 [7b80942](https://github.com/LingCoder/OnJava8/commit/7b8094287411818b64e35a75055c9f7272733dea)
> > > [下载](http://106.54.187.105:8181/book.zip)
> 
> 非常感谢

原地址下不到了，请问能帮忙转发一份么？jian0706_zh@163.com

**Comment by anuger** [comment]
> > > @flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了
> > > > 已更新到 [7b80942](https://github.com/LingCoder/OnJava8/commit/7b8094287411818b64e35a75055c9f7272733dea)
> > > > [下载](http://106.54.187.105:8181/book.zip)
> > 
> > 
> > 非常感谢
> 
> 原地址下不到了，请问能帮忙转发一份么？[jian0706_zh@163.com](mailto:jian0706_zh@163.com)

我发给你哈,更新服务器忘记起服务了

**Comment by zhOrange** [comment]
> > > > @flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了
> > > > > 已更新到 [7b80942](https://github.com/LingCoder/OnJava8/commit/7b8094287411818b64e35a75055c9f7272733dea)
> > > > > [下载](http://106.54.187.105:8181/book.zip)
> > > 
> > > 
> > > 非常感谢
> > 
> > 
> > 原地址下不到了，请问能帮忙转发一份么？[jian0706_zh@163.com](mailto:jian0706_zh@163.com)
> 
> 我发给你哈,更新服务器忘记起服务了

太感谢您了~多谢!

**Comment by pobc** [comment]
> @flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了
> 
> > 已更新到 [7b80942](https://github.com/LingCoder/OnJava8/commit/7b8094287411818b64e35a75055c9f7272733dea)
> > [下载](http://106.54.187.105:8181/book.zip)

firejiang@hotmail.com 下载地址无法访问了，麻烦发我一份

**Comment by yinyy111** [comment]
yyyidyf@gmail.com 下载地址无法访问了&nbsp; 麻烦发我一份&nbsp; Thanks♪(･ω･)ﾉ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pobc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 下午5:56
收件人:&nbsp;"LingCoder/OnJava8"<OnJava8@noreply.github.com&gt;;
抄送:&nbsp;"阿浪"<yyy_email@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LingCoder/OnJava8] 可以发一下电子版吗 (#7)





  
@flyzyh 晚上我再更新一下最新版本哈,上面那个版本有点落后了
  
已更新到 7b80942
 下载
   
firejiang@hotmail.com 下载地址无法访问了，麻烦发我一份

**Comment by amyxin** [comment]
> > > [mobi](http://106.54.187.105:8181/book.mobi)下载
> > 
> > 
> > 咦？怎么下载不到了？是我来晚了吗。。。。。
> 
> 不好意思哈,重启机器忘记起服务了,现在可以了 @flyzyh

大佬地址无法访问了，能发我邮箱吗，非常感谢。896123009@qq.com

**Comment by anuger** [comment]
我放到了[微云](https://share.weiyun.com/LRbiYBiw)一份,下载速度可能有点慢,我的机器经常重启,对不能下载的同学说声抱歉哈

**Comment by yinyy111** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"An"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 下午5:04
收件人:&nbsp;"LingCoder/OnJava8"<OnJava8@noreply.github.com&gt;;
抄送:&nbsp;"阿浪"<yyy_email@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LingCoder/OnJava8] 可以发一下电子版吗 (#7)





 
我放到了微云一份,下载速度可能有点慢,我的机器经常重启,对不能下载的同学说声抱歉哈

**Comment by swhzzh** [comment]
> 我放到了[微云](https://share.weiyun.com/LRbiYBiw)一份,下载速度可能有点慢,我的机器经常重启,对不能下载的同学说声抱歉哈

微云的链接失效了, 可以发给我一份吗? 2521285258@qq.com, 多谢!

**Comment by anuger** [comment]
> > 我放到了[微云](https://share.weiyun.com/LRbiYBiw)一份,下载速度可能有点慢,我的机器经常重启,对不能下载的同学说声抱歉哈
> 
> 微云的链接失效了, 可以发给我一份吗? [2521285258@qq.com](mailto:2521285258@qq.com), 多谢!

不要意思把那个取消了,现在可以下载了,不过上面那个有点落后,[这里](https://anuger.cn/blog/2)有最后提交的下载地址

**Comment by swhzzh** [comment]
> > > 我放到了[微云](https://share.weiyun.com/LRbiYBiw)一份,下载速度可能有点慢,我的机器经常重启,对不能下载的同学说声抱歉哈
> > 
> > 
> > 微云的链接失效了, 可以发给我一份吗? [2521285258@qq.com](mailto:2521285258@qq.com), 多谢!
> 
> 不要意思把那个取消了,现在可以下载了,不过上面那个有点落后,[这里](https://anuger.cn/blog/2)有最后提交的下载地址

多谢分享!

**Comment by liang-kan** [comment]
> > > > > > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > > > > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > > > > > 
> > > > > > 
> > > > > > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> > > > > 
> > > > > 
> > > > > 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你
> > > > 
> > > > 
> > > > 能发给我一份吗
> > > 
> > > 
> > > 邮箱地址
> > 
> > 
> > 你好，麻烦你发我一份，谢谢
> > [744883037@qq.com](mailto:744883037@qq.com)
> > 感谢🙏
> 
> [869329190@qq.com](mailto:869329190@qq.com)
> 同求!感谢了

同求：1466380831.@qq.com

**Comment by a471640241** [comment]
> > > > > > > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > > > > > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> > > > > > 
> > > > > > 
> > > > > > 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你
> > > > > 
> > > > > 
> > > > > 能发给我一份吗
> > > > 
> > > > 
> > > > 邮箱地址
> > > 
> > > 
> > > 你好，麻烦你发我一份，谢谢
> > > [744883037@qq.com](mailto:744883037@qq.com)
> > > 感谢🙏
> > 
> > 
> > [869329190@qq.com](mailto:869329190@qq.com)
> > 同求!感谢了
> 
> 同求：[1466380831.@qq.com](mailto:1466380831.@qq.com)

百度网盘地址 链接: https://pan.baidu.com/s/1ZYNv-aoviwXBmE2XSD5REg 提取码: urcd

**Comment by yy35959199** [comment]
> > > > > > > > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > > > > > > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> > > > > > > 
> > > > > > > 
> > > > > > > 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你
> > > > > > 
> > > > > > 
> > > > > > 能发给我一份吗
> > > > > 
> > > > > 
> > > > > 邮箱地址
> > > > 
> > > > 
> > > > 你好，麻烦你发我一份，谢谢
> > > > [744883037@qq.com](mailto:744883037@qq.com)
> > > > 感谢🙏
> > > 
> > > 
> > > [869329190@qq.com](mailto:869329190@qq.com)
> > > 同求!感谢了
> > 
> > 
> > 同求：[1466380831.@qq.com](mailto:1466380831.@qq.com)
> 
> 百度网盘地址 链接: [https://pan.baidu.com/s/1ZYNv-aoviwXBmE2XSD5REg](https://pan.baidu.com/s/1ZYNv-aoviwXBmE2XSD5REg#urcd) 提取码: urcd

感谢

**Comment by sky508** [comment]
> > > 请问gitbook使用的版本是哪个? 我用最新版的gitbook-cli 2.3.2 gitbook是3.2.3 ,使用命令gitbook build 可以生成静态页面 但是打开点击内容的链接不会跳转到对应的页面. 使用命名 gitbook pdf 或者是其他格式都会报错,错误如下
> > > ![image](https://user-images.githubusercontent.com/11511810/67101270-e4d4a980-f1f3-11e9-9f00-8a2b38195ff3.png)
> > 
> > 
> > 我也是你这样，你解决了吗，急需电子版，需要在ipad上看啊。
> 
> 我也是在iPad上面看的,我在一个群里找到了,还不错,邮箱发一下,我发给你

你好，能发我一份吗？邮箱17730269920@163.com，万分感谢！

**Comment by yfShy** [comment]
您好 我也想在iPad上看。能发一下吗。 谢谢谢谢谢谢。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;sky508&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月15日(星期二) 上午9:13
收件人:&nbsp;&quot;LingCoder/OnJava8&quot;<OnJava8@noreply.github.com&gt;;
抄送:&nbsp;&quot;yfShy&quot;<yyy_email@foxmail.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LingCoder/OnJava8] 可以发一下电子版吗 (#7)

**Comment by EruDev** [comment]
有原版吗，google 了一圈没找到- - @LingCoder
