### ISSUE TITLE
第十章 接口

### ISSUE THREAD

**Issue by TineWindy** [LingCoder/OnJava8#81]
###  申请翻译/校对

第十章 接口
  * 翻译

### 具体章节/标题

* 第十章 接口
  *  抽象类和方法
  *  接口创建
  * 抽象类和接口
  * 完全解耦
  * 多接口结合
  * 使用继承扩展接口
  * 接口适配
  * 接口字段
  * 接口嵌套
  * 接口和工厂方法模式
  * 本章小结

**Comment by blackwatchcup** [comment]
请问现在翻译到哪里了，可以一起参与一下吗？

**Comment by sjsdfg** [comment]
@xiangflight  翻译完成
