### ISSUE TITLE
第二十五章 设计模式

### ISSUE THREAD

**Issue by jason31520** [LingCoder/OnJava8#98]
###  申请翻译/校对

  * 翻译

### 具体章节/标题

* 第二十五章 设计模式
  * 概念
  * 构建型	
  * 面向实施	
  * 工厂模式	
  * 函数对象
  * 接口改变
  * 解释器
  * 回调
  * 多次调度
  * 模式重构
  * 抽象用法
  * 多次派遣
  * 访问者模式
  * RTTI的优劣
  * 本章小结

**Comment by sjsdfg** [comment]
他人重新认领
